version: '3'

services:
  web: 
   build: 
     context: .
     dockerfile: Dockerfile.dev
   container_name: react-frontend
   ports:
     - "3000:3000"
   volumes:
     - "/app/node_modules"
    #  Any changes you make in your local machine will synchronize the changes in the
   # container
     - .:/app